name: Patch build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
         submodules: recursive
      
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install python3-numpy
        
      - name: Build patch archive
        run: bash build.sh
        
      - name: Release
        run: gh release create v${{ github.RUN_NUMBER }} patch.zip
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
