name: Patch build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
         submodules: recursive
      
      - name: Install numpy
        run: sudo apt install python3-numpy
        
      - name: Build patch archive
        run: bash build.sh
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
         files: patch.zip
         tag_name: v${{ github.run_number }}
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
