name: Release build

on:
  workflow_dispatch:
    inputs:
      version:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
        
      - name: Build patch archives
        run: bash build.sh
        
      - name: Release
        run: gh release create v$VERSION patch_atmos.zip patch_yuzu.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.event.inputs.version }}
